apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: polaris-platform
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/mathii0402/Polaris.git
    targetRevision: main
    path: platform/addons

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      selfHeal: true
      prune: true
