apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocd-manager
  labels:
    app.kubernetes.io/name: argocd
    app.kubernetes.io/component: rbac
    app.kubernetes.io/part-of: platform
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
- nonResourceURLs: ["*"]
  verbs: ["*"]